-- Synthetic administrative contract fixture. Never deploy this schema.
create role anon;
create role authenticated;
create role krow_pilot_service;
create schema auth;
create schema private;
create schema storage;
create schema krow_pilot;
create table auth.users(id uuid primary key,raw_app_meta_data jsonb not null default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table public.users(uuid uuid primary key references auth.users(id),full_name text,email_address text unique,institutional_id text,is_active boolean default true,deleted_at timestamptz);
create table public.driver_profiles(driver_id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.users(uuid),license_number text not null,license_expiry date not null,status text not null default 'pending' check(status in('pending','approved','rejected','suspended')),rating numeric);
create table public.vehicles(vehicle_id uuid primary key default gen_random_uuid(),driver_id uuid not null references public.driver_profiles(driver_id),license_plate text not null unique,brand text not null,model text not null,car_year integer not null,car_color text not null,capacity integer not null check(capacity>0),is_active boolean not null default true);
create table public.rides(ride_id uuid primary key default gen_random_uuid(),driver_id uuid references public.driver_profiles(driver_id),vehicle_id uuid references public.vehicles(vehicle_id),origin_lat numeric,origin_lng numeric,destination_lat numeric,destination_lng numeric,origin_address text,destination_address text,departure_time timestamptz,created_at timestamptz default now(),status text,price_per_seat numeric,available_seats integer,version integer default 1,route_polyline text,route_distance_meters integer,route_duration_seconds integer,route_provider text);
create table public.transport_stops(stop_id uuid primary key,name text);
create table public.ride_stops(stop_id uuid primary key,ride_id uuid references public.rides(ride_id),lat numeric,lng numeric,address text,stop_order integer,transport_stop_id uuid references public.transport_stops(stop_id),route_version integer default 1,is_active boolean default true);
create table public.bookings(booking_id uuid primary key,ride_id uuid references public.rides(ride_id),user_id uuid references public.users(uuid),pickup_stop_id uuid references public.ride_stops(stop_id),dropoff_stop_id uuid references public.ride_stops(stop_id),seats_reserved integer default 1,status text,created_at timestamptz default now());
create table public.ride_status_history(id uuid primary key default gen_random_uuid(),ride_id uuid references public.rides(ride_id),status text,previous_status text,actor_id uuid references auth.users(id),reason text,changed_at timestamptz default now());
create table krow_pilot.booking_prices(booking_id uuid primary key references public.bookings(booking_id),amount_cents integer);
create table krow_pilot.cash(booking_id uuid primary key references public.bookings(booking_id),amount_cents integer,status text);
create table storage.buckets(id text primary key,name text,public boolean default false,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);
alter table storage.objects enable row level security;
grant usage on schema public,krow_pilot,storage to krow_pilot_service;
-- Match production privileges explicitly; a blanket grant masks missing joins.
grant select on public.users,public.driver_profiles,public.vehicles,public.rides,public.ride_stops,public.bookings,public.ride_status_history,krow_pilot.booking_prices,krow_pilot.cash to krow_pilot_service;
grant update(full_name) on public.users to krow_pilot_service;
grant update(rating) on public.driver_profiles to krow_pilot_service;
grant usage on schema storage to authenticated;
grant select,insert on storage.objects to authenticated;
grant execute on function auth.uid() to authenticated,krow_pilot_service;
grant usage on schema auth to authenticated,krow_pilot_service;
alter table public.users enable row level security;
alter table public.driver_profiles enable row level security;
alter table public.vehicles enable row level security;
alter table public.ride_status_history enable row level security;
alter table public.transport_stops enable row level security;
create policy fixture_catalog_authenticated_read on public.transport_stops for select to authenticated using((select auth.uid()) is not null);
create policy fixture_user_runtime on public.users to krow_pilot_service using(true) with check(true);
create policy fixture_driver_runtime_select on public.driver_profiles for select to krow_pilot_service using(true);
create policy fixture_driver_runtime_update on public.driver_profiles for update to krow_pilot_service using(true) with check(true);
create policy fixture_vehicle_runtime_select on public.vehicles for select to krow_pilot_service using(true);
